<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <IsPackable>false</IsPackable>
    <!--
    https://github.com/dotnet/winforms/blob/main/docs/designer/designer-high-dpi-mode.md
    -->
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MACTrackBarLib\MACTrackBarLib.csproj" />
  </ItemGroup>

</Project>